version: '3.8'

services:
#  app:
#    build: ./app
#    container_name: neurolog_app
#    platform: linux/amd64
#    restart: always
#    environment:
#      - NODE_ENV=development
#    volumes:
#      - ./app:/app
#    ports:
#      - "5173:5173"
#    command: npm run dev -- --host

  api:
    build: ./api
    container_name: neurolog_api
    restart: always
    environment:
      - APP_ENV=local
      - DB_HOST=db
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_ROOT_PASSWORD=${DB_ROOT_DATABASE}
    depends_on:
      - db
    volumes:
      - ./api:/var/www/html
    expose:
      - "${API_PORT}:9000"

  nginx:
    image: nginx:stable
    container_name: neurolog_nginx
    restart: always
    ports:
      - "${API_PORT}:80"
    volumes:
      - ./api:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

  db:
    image: mysql:8.0
    container_name: neurolog_db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_DATABASE}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./dbdata:/var/lib/mysql

volumes:
  dbdata:
